# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageRepository: 'pocust'
  dockerFilePath: '**/Dockerfile'
  vmImageName: 'ubuntu-latest'

pool: Default

stages:
- stage: Check
  displayName: Check Stage
  pool: 'Python Pool'
  jobs:
    - job: Check
      displayName: Code Check
      steps:
        - task: UseNode@1
          inputs:
            version: '12.13.0'
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.7.3'
            addToPath: true
            architecture: 'x64'
        - task: SonarCloudPrepare@1
          inputs:
            SonarCloud: 'SonarCloud'
            organization: 'andywardust'
            scannerMode: 'CLI'
            configMode: 'file'

        - task: SonarCloudAnalyze@1

        - task: SonarCloudPublish@1
          inputs:
            pollingTimeoutSec: '180'

        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: 'python -V'


- stage: Build
  displayName: Build Stage
  pool: 'Docker Pool'
  jobs:
    - job: Build
      displayName: Build
      steps:
        - task: Docker@2
          inputs:
            repository: $(imageRepository)
            command: 'build'
            Dockerfile: '$(dockerfilePath)'
            tags: '$(tag)'






