# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageRepository: 'ustpoc-docker-local.jfrog.io/pocust'
  dockerFilePath: '**/Dockerfile'
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

stages:
- stage: Import
  displayName: Import Requirements
  jobs:
    - job: Import
      displayName: jFrog Import
      steps:
        - task: ArtifactoryToolsInstaller@1
          displayName: Install jFrog Client from Artifactory
          inputs:
            artifactoryService: 'jFrog'
            cliInstallationRepo: 'jfrog-cli'

- stage: Check
  displayName: Check Stage
  jobs:
    - job: Check
      displayName: Code Check
      steps:
        - task: SonarCloudPrepare@1
          inputs:
            SonarCloud: 'SonarCloud'
            organization: 'andywardust'
            scannerMode: 'CLI'
            configMode: 'file'

        - task: SonarCloudAnalyze@1

        - task: SonarCloudPublish@1
          inputs:
            pollingTimeoutSec: '180'

        - script: |
            curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
            java -jar wss-unified-agent.jar
          displayName: 'whitesource check'

